name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up environment variables
        run: |
          echo "POSTGRESQL_HOST=${{ vars.POSTGRESQL_HOST }}" > ./scraper/.env
          echo "POSTGRESQL_PORT=${{ vars.POSTGRESQL_PORT }}" >> ./scraper/.env
          echo "POSTGRESQL_USER=${{ vars.POSTGRESQL_USER }}" >> ./scraper/.env
          echo "POSTGRESQL_PASSWORD=${{ vars.POSTGRESQL_PASSWORD }}" >> ./scraper/.env
          echo "POSTGRESQL_DATABASE=${{ vars.POSTGRESQL_DATABASE }}" >> ./scraper/.env
          echo "POSTGRESQL_TABLE=${{ vars.POSTGRESQL_TABLE }}" >> ./scraper/.env

      - name: Build and run containers
        run: |
          export IMAGE_NAME="jobs-app:${GITHUB_SHA}"
          docker compose down
          
          # Clean up old unused images
          docker compose build
          docker compose up -d --remove-orphans

      - name: Show running containers
        run: docker ps
